### PR TITLE
bump syft and grype versions

### PR DESCRIPTION
**Pull request by spiffcs**
## Bump syft and grype to latest versions
- add distro coverage for rockylinux and mariner 
- add php exception for language coverage

Signed-off-by: Christopher Angelo Phillips <christopher.phillips@anchore.com>

### CODE REVIEW

**Review by jonasagx — APPROVED** [review]

**Comment by spiffcs** [comment]
cc @luhring @wagoodman  <-- Thanks @jonasagx for the first look!

**Review by nightfurys — COMMENTED** [review]
@spiffcs Rocky Linux os packages are matched to vulnerabilities from the rhel feed. That mapping needs to be added. I've got a branch with the [changes](https://github.com/anchore/grype-db/commit/d23b4811054abf7a623e9fe4156f953388cae77e) I can either add it to this PR or open a new PR, up to you

**Comment by spiffcs** [comment]
@nightfurys just added a commit that pulls in that change

Is there a similar mapping needed for:
```
		{
			dist:     distro.Mariner,
			version:  "1.0.20211114-1.0",
			expected: "mariner:1.0.20211114-1.0",
		},
```

**Review by nightfurys — APPROVED** [review]
Looks good to me. Thank you for following up on the mariner-feed mapping question

**Pull request merged**
